/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author manoel cardoso
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private static TelaTarefas telaTarefas;
    private static TelaPesquisar telaPesquisar;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        setExtendedState(MAXIMIZED_BOTH);
        atalhoGlobal();
        setIconImage(new ImageIcon(getClass().getResource("/imagem/logo.png")).getImage());
        mostrarDAtaHora();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jLbDataHora = new javax.swing.JLabel();
        jBtChamarTarefas = new javax.swing.JButton();
        jBtChamarPesquisas = new javax.swing.JButton();
        jBtFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRBMSobre = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tela Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowFechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jToolBar1.setBackground(new java.awt.Color(0, 255, 102));
        jToolBar1.setRollover(true);
        jToolBar1.setEnabled(false);
        jToolBar1.add(jLbDataHora);

        jBtChamarTarefas.setText("Terefa");
        jBtChamarTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionChamaTarefa(evt);
            }
        });
        jToolBar1.add(jBtChamarTarefas);

        jBtChamarPesquisas.setText("Pesquisar");
        jBtChamarPesquisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionChamarPesquisas(evt);
            }
        });
        jToolBar1.add(jBtChamarPesquisas);

        jBtFechar.setText("Fechar");
        jBtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtFecharActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtFechar);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/verified-no-background.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jMenu1.setText("Arquivo");

        jRadioButtonMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Adicionar Tarefas");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAddTarefa(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Pesquisar Tarefas");
        jRadioButtonMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPesTarefa(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");

        jRBMSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jRBMSobre.setSelected(true);
        jRBMSobre.setText("ajuda");
        jRBMSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-exclamação-10.png"))); // NOI18N
        jRBMSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAjuda(evt);
            }
        });
        jMenu2.add(jRBMSobre);

        jRadioButtonMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("Sobre");
        jRadioButtonMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-ponto-de-interrogação-10.png"))); // NOI18N
        jRadioButtonMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSobre(evt);
            }
        });
        jMenu2.add(jRadioButtonMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Sair");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionBoxSair(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionChamaTarefa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionChamaTarefa
        chamarTarefas();
       
    }//GEN-LAST:event_actionChamaTarefa

    private void actionChamarPesquisas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionChamarPesquisas
        chamarPesquisas();
        
    }//GEN-LAST:event_actionChamarPesquisas

    private void jBtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtFecharActionPerformed
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        
        int op = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(op == 0){
            this.dispose();
        }        
    }//GEN-LAST:event_jBtFecharActionPerformed

    private void actionSobre(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSobre
        JOptionPane.showMessageDialog(null, "Controle de tarefas 1.0.\n "
                + "Desenvolvimento em java com MySQL.\n "
                + "Densenvolvedor Vitor. ", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_actionSobre

    private void actionAjuda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAjuda
         JOptionPane.showMessageDialog(null, "Email: vitorxd1@gmail.com \n "
                + "Inserir print(s) do(s) erro(s).\n "
                + "Densenvolvedor Vitor. ", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_actionAjuda

    private void actionBoxSair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionBoxSair
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        
        int op = JOptionPane.showConfirmDialog(null, "Deseja encerrar a aplicação?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(op == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_actionBoxSair

    private void actionAddTarefa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAddTarefa
    chamarTarefas();
    }//GEN-LAST:event_actionAddTarefa

    private void actionPesTarefa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPesTarefa
    chamarPesquisas();
    }//GEN-LAST:event_actionPesTarefa

    private void windowFechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowFechar
        UIManager.put("OptionPane.yesButtonText", "Sim");
        UIManager.put("OptionPane.noButtonText", "Não");
        
        int op = JOptionPane.showConfirmDialog(null, "Deseja encerrar a sessão", "Sair", JOptionPane.YES_NO_OPTION);
        if(op == 0){
            this.dispose();
        }   
    }//GEN-LAST:event_windowFechar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtChamarPesquisas;
    private javax.swing.JButton jBtChamarTarefas;
    private javax.swing.JButton jBtFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbDataHora;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRBMSobre;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public static void chamarTarefas() {
        if (telaTarefas == null) {
            telaTarefas = new TelaTarefas();
        }
        telaTarefas.setVisible(true);
        
        
        
    }

    public static void chamarPesquisas() {
        if (telaPesquisar == null){
            telaPesquisar = new TelaPesquisar();
        }
        telaPesquisar.setVisible(true);
            
    }

    private void atalhoGlobal() {
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                if(e.getID()==KeyEvent.KEY_PRESSED
                    && e.isControlDown()
                    && e.getKeyCode() == KeyEvent.VK_B){
                    chamarPesquisas();//Carregar a tela de pesquisa.
                    return false;//BLoquei a propagação(opcional).
                }if(e.getID()==KeyEvent.KEY_PRESSED
                    && e.isControlDown()
                    && e.getKeyCode() == KeyEvent.VK_A){
                    chamarTarefas();//Carregar a tela de pesquisa.
                    return false;//BLoquei a propagação(opcional).
                }
                return false;
            }
        });
    }

    private void mostrarDAtaHora() {
        LocalDateTime agora = LocalDateTime.now();
        DateTimeFormatter formatoBR = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        jLbDataHora.setText(agora.format(formatoBR));
    }
}
